### ISSUE TITLE
Add android 7 support if possible

### ISSUE THREAD

**Issue by tony-0tis** [DSteve595/EmojiSwitcher#12]
Androind N(7.0), Wileyfox swift, SuperSU 2.78 SR1 Beta, Buzybox 43, Current emoji not detected.
Install and reboot has no effect.

**Comment by DSteve595** [comment]
This is probably because RootTools, the library I'm using for most root operations, isn't compatible with newer versions of SuperSU, which is what most people are using (and as far as I know is the only root solution on 7.0). I've been looking for a replacement, but I might end up rolling my own. Really not looking forward to that after seeing how complicated the logic can be (especially with file operations and remounting filesystems).

**Comment by DSteve595** [comment]
Hey,
Unfortunately, some things have changed in Android 7.0 that make it a
little tougher to get this done. I'm working on it though, and it shouldn't
be too much longer.

Steven

**Comment by Sammichoux** [comment]
Right, I'm more than happy to be able to switch emojis. The unknown issue's a tiny detail, not worth the headaches.
