### ISSUE TITLE
Push last versions of Emoji Switcher on Github

### ISSUE THREAD

**Issue by NerosTie** [DSteve595/EmojiSwitcher#17]
Why can we download the version 2.1.5 on Google Play but here the last version is only 2.1.2? And if there is an update, where are the commits with the new stuff?

Thanks.

**Comment by henrebotha** [comment]
The update on 17 May (not sure of the version number) is reporting the presence of malware. So I'm guessing they moved the main project hosting off of Github in order to prevent people from seeing the malware in the code. I mean, it's possible that that's not the reason, but it looks awfully shady...

**Comment by NerosTie** [comment]
That's why I don't use this app anymore. It's shady and it should be removed from the Google store.

**Comment by DSteve595** [comment]
Hey, sorry for the lack of updates.
Earlier this year, I sold the app to an advertising firm. They now control the store listing, but hosting hasn't been switched over. If you're nervous about what they might've added, you can actually still use the latest version from here (or compile it yourself) and you should have no problems.
I've confronted them about the malware warnings, and they told me they're looking into it, but unfortunately I really don't have control over the store version anymore.
